name: Most helpful contributors

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - run: node dist/most-helpful-contributors.js ${{ env.DISCUSSION_ID }} ${{ secrets.PAT }}
        env:
          DISCUSSION_ID: D_kwDOHOfQ684AUUSB
